Update the mirror script to use git.

diff --git a/selfupdate-server/finkgitup b/selfupdate-server/finkgitup
--- a/selfupdate-server/finkgitup
+++ b/selfupdate-server/finkgitup
@@ -1,30 +1,24 @@
 #!/bin/sh
 
+# Config
 FIROOT="/Volumes/src2/fink/selfupdate"
+REPO="https://github.com/danielj7/fink-dists.git"
 LOCKFILE="/var/run/finkrsyncup.lock"
-SSHUSER="finkcvs"
-CVSARGS=""
 
 usage() {
 	cat > "/dev/stderr" << EOF
-usage: $0 [-l lockfile] [-o outputdir]
+usage: ${0} [-l lockfile] [-o outputdir]
 EOF
-	exit
+	exit 1
 }
 
-while getopts ":l:o:u:hq" OPTION; do
+while getopts ":l:o:h" OPTION; do
 	case "${OPTION}" in
 		l)
-			LOCKFILE=${OPTARG}
+			LOCKFILE="${OPTARG}"
 			;;
 		o)
-			FIROOT=${OPTARG}
-			;;
-		u)
-			SSHUSER=${OPTARG}
-			;;
-		q)
-			CVSARGS=" -q "
+			FIROOT="${OPTARG}"
 			;;
 		h | ?)
 			usage
@@ -32,16 +26,45 @@ while getopts ":l:o:u:hq" OPTION; do
 	esac
 done
 
-export CVS_RSH=ssh
-
+# Prevent more than one concurrent update
 lockfile -r 0 "${LOCKFILE}" || exit 0
 
 cd "${FIROOT}"
 
-if /usr/bin/cvs -d :ext:${SSHUSER}@fink.cvs.sourceforge.net:/cvsroot/fink ${CVSARGS} -z3 co -d finkinfo.tmp dists; then
-	if rsync -a --delete --exclude=.cvsignore --exclude=CVS "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"; then
-		echo "$(date -u +%s)" > "${FIROOT}/finkinfo/TIMESTAMP";
-	fi;
+if [ ! -d "${FIROOT}/finkinfo.tmp/.git" ]; then
+	if [ -d "${FIROOT}/finkinfo.tmp"]; then
+		rm -fr "${FIROOT}/finkinfo.tmp"
+	fi
+	if ! git clone ${REPO} finkinfo.tmp; then
+		echo "clone did not succeed, aborting." >&2
+		rm -fr "${LOCKFILE}" "${FIROOT}/finkinfo.tmp"
+		exit 1
+	fi
 fi
 
+# Enter the git repo
+cd "${FIROOT}/finkinfo.tmp"
+
+if ! git fetch origin; then
+	# We are depending on git to self recover, if it does not, you likely have deeper issues.
+	echo "fetch did not succeed, aborting." >&2
+	rm -f "${LOCKFILE}"
+	exit 1
+fi
+# Be sure we are in the right branch and then update.
+git checkout master
+git reset --hard origin/master
+
+# Exit the git repo
+cd "${FIROOT}"
+
+# Make a clean copy out of the git repo
+rsync -a --delete --exclude=".cvsignore" --exclude=".gitignore" --exclude=".DS_Store" "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"
+
+# Add the timestamp
+echo "$(date -u +%s)" > "${FIROOT}/finkinfo/TIMESTAMP"
+
+# Clean up
 rm -f "${LOCKFILE}"
+
+exit 0
