Add a timeout for cvs and generate the proper timestamps.

diff --git a/selfupdate-server/finkcvsup b/selfupdate-server/finkcvsup
--- a/selfupdate-server/finkcvsup
+++ b/selfupdate-server/finkcvsup
@@ -1,9 +1,12 @@
 #!/bin/sh
 
+# Config
 FIROOT="/Volumes/src2/fink/selfupdate"
 LOCKFILE="/var/run/finkrsyncup.lock"
 SSHUSER="finkcvs"
 CVSARGS=""
+TIMEOUT="timeout"
+export CVS_RSH=ssh
 
 usage() {
 	cat > "/dev/stderr" << EOF
@@ -36,16 +39,31 @@ while getopts ":l:o:u:q" OPTION; do
 	esac
 done
 
-export CVS_RSH=ssh
-
+# Prevent more than one concurrent update
 lockfile -r 0 "${LOCKFILE}" || exit 0
 
 cd "${FIROOT}"
 
-if /usr/bin/cvs -d :ext:${SSHUSER}@fink.cvs.sourceforge.net:/cvsroot/fink ${CVSARGS} -z3 co -d finkinfo.tmp dists; then
-	if rsync -a --delete --exclude=.cvsignore --exclude=CVS "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"; then
-		echo "$(date -u +%s)" > "${FIROOT}/finkinfo/TIMESTAMP";
-	fi;
+# Note the start time of a new fetch
+echo "$(date -u +%s)" > "${FIROOT}/finkinfo/UPDATE"
+
+# Update from cvs with a 10 min timeout
+if ! ${TIMEOUT} --preserve-status -k 10s 10m cvs -d :ext:${SSHUSER}@fink.cvs.sourceforge.net:/cvsroot/fink ${CVSARGS} -z3 co -d finkinfo.tmp dists; then
+	echo "fetch did not succeed, aborting." >&2
+	rm -f "${LOCKFILE}"
+	exit 1
 fi
 
+# Make a clean copy out of the cvs repo
+if ! rsync -a --delete --exclude=.cvsignore --exclude=CVS "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"; then
+	rm -f "${LOCKFILE}"
+	exit 1
+fi
+
+# Add the timestamp
+date -u +%s | tee "${FIROOT}/finkinfo/TIMESTAMP" > "${FIROOT}/finkinfo/LOCAL"
+
+# Clean up
 rm -f "${LOCKFILE}"
+
+exit 0
